# Generated by Django 5.1.7 on 2025-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_zx2qdz', upload_to='images/'),
        ),
    ]
